gai/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from gai import settings

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'gai.views.home', name='home'),
    # url(r'^gai/', include('gai.foo.urls')),
    url(r'^$', 'gai.views.index'),
    url(r'^([BrAmnHPqRjibCe2ghYMW5XufzUTNxVZvt9EKFdyJ7D8SLa4p6w3QsckG]{2,})$',
        'gai.views.default_redirect'),
    url(r'^a/shorten$', 'gai.views.shorten_url'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^a/admin/', include(admin.site.urls)),
)

gai/models.py
from django.db import models


class Url(models.Model):
    origin = models.URLField(max_length=2083)
    hash = models.CharField(max_length=40, unique=True)
    short = models.CharField(max_length=11, null=True, blank=True)
    access_count = models.PositiveIntegerField(default=0)
    created_by = models.GenericIPAddressField()
    created_on = models.DateTimeField(auto_now_add=True)


class AccessLog(models.Model):
    url = models.ForeignKey('Url', related_name='access_logs')
    ip = models.GenericIPAddressField()
    useragent = models.ForeignKey('UserAgent', related_name='access_logs')
    access_on = models.DateTimeField(auto_now_add=True)


class UserAgent(models.Model):
    hash = models.CharField(max_length=40, unique=True)
    text = models.TextField()

gai/views.py
import hashlib

from django import forms
from django.http import Http404
from django.db.models import Sum
from django.http import (
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseForbidden,
)
from django.shortcuts import (
    get_object_or_404,
    redirect,
    render_to_response,
)
from django.template import RequestContext
from django.utils import simplejson as json

from gai.base56 import (
    mmi_hash,
    mmi_unhash,
)
from gai.models import (
    Url,
    AccessLog,
    UserAgent
)
from gai.settings import (
    MIN_LENGTH,
    SITE_TITLE,
    SITE_SUBTITLE,
    GAI_VERSION,
)


class UrlForm(forms.ModelForm):

    class Meta:
        model = Url
        fields = ('origin', )


def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip


def default_redirect(request, short):
    if len(short) < MIN_LENGTH:
        return HttpResponseNotFound()
    try:
        pk = mmi_unhash(short)
    except:
        raise Http404
    url = get_object_or_404(Url, id=pk)
    ip = get_client_ip(request)
    ua_text = request.META.get('HTTP_USER_AGENT')
    ua_hash = hashlib.sha1(ua_text).hexdigest()
    ua, created = UserAgent.objects.get_or_create(hash=ua_hash,
        defaults={'text': ua_text})
    new_access_log = AccessLog.objects.create(url=url, ip=ip,
        useragent=ua)
    url.access_logs.add(new_access_log)
    url.access_count += 1
    url.save()
    return redirect(url.origin)


def shorten_url(request):
    if request.POST:
        form = UrlForm(request.POST)
        if form.is_valid():
            origin = form.cleaned_data['origin']
            url_hash = hashlib.sha1(origin).hexdigest()
            try:
                url = Url.objects.get(hash=url_hash)
                new = False
            except Url.DoesNotExist:
                new = True
                url = Url.objects.create(origin=origin, hash=url_hash,
                    created_by=get_client_ip(request))
                url.short= mmi_hash(url.id)
                url.save()
            return HttpResponse(json.dumps({'is_new': new, 'shorten': url.short}),
                mimetype="application/json")
        return HttpResponseBadRequest(form.errors['origin'])
    raise Http404


def index(request):
    site_title = SITE_TITLE
    site_subtitle = SITE_SUBTITLE
    version = GAI_VERSION
    form = UrlForm()
    amount_of_urls = Url.objects.count()
    total_access_count = Url.objects.aggregate(tc=Sum('access_count'))['tc']
    return render_to_response('index.html', locals(),
                              context_instance=RequestContext(request))

gai/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<head>
  <title>{{ site_title }} / Yet Another URL Shortening Service</title>
  <style type="text/css">
    body {
      font-family: sans-serif;
      background: #f3f3f3;
      color: #555;
    }
    .container {
      width: 800px;
      margin: 0 auto;
    }
    #main {
      margin-top: 80px;
      border: 1px solid #ccc;
      padding: 20px;
      background: #fbfbfb;
    }
    #main h1 {
      text-align: center;
      font-size: 48px;
      margin: 0;
    }
    #id_origin {
      color: #555;
      width: 680px;
      font-family: sans-serif;
      border: 1px solid #ccc;
      padding: 8px;
      font-size: 16px;
      transition: all 0.5s ease;
    }
    #id_origin:focus {
      box-shadow: inset 0 0 4px #ccc;
      border: 1px solid #aaa;
    }
    input[type=submit] {
      color: #555;
      font-family: sans-serif;
      font-size: 16px;
      background: #f3f3f3;
      width: 97px;
      padding: 8px;
      border: 1px solid #ccc;
      transition: all 0.5s ease;
    }
    input[type=submit]:hover {
      border: 1px solid #aaa;
      background: #fbfbfb;
    }
    #result {
      font-size: 18px;
      font-weight: bold;
      background: #fbfbfb;
      margin: 14px auto;
      border: none;
      border-bottom: 1px solid #ccc;
      color: #555;
      font-family: sans-serif;
      display: block;
      width: 20em;
      padding: 6px;
      text-align: center;
    }
    #errors p {
      color: #BD2D30;
      display: none;
    }
  </style>
</head>
<body>
<div id="main" class="container">
  <h1>{{ site_title }}</h1>
  <p style="text-align:center">{{ site_subtitle|safe }}</p>
  <form id="shorten" action="/a/shorten" method="post">
    {% csrf_token %}
    {{ form.origin }}
    <input id="submit" type="submit" value="Shorten">
    <input id="result" type="text">
    <div id="errors">
      <p id="error-invalid">Please enter a valid URL.</p>
      <p id="error-busy">The server is busy, please retry later.</p>
    </div>
  </form>
</div>
<footer class="container">
  <p><small>Powered by Gai {{ version }}, shortened <span id="amount">{{ amount_of_urls }}</span> urls that have been accessed {{ total_access_count }} times.</small></p>
</footer>
<script src="{% static "jquery.min.js" %}"></script>
<script src="{% static "functions.js" %}"></script>
</body>